name: parkquest_parkir_gamifikasi
description: "Project PBL Semester 3"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  flutter_rating_bar: ^4.0.1
  video_player: ^2.9.2
  get: ^4.6.6
  http: ^1.2.2
  get_storage: ^2.1.1
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - .env
